# 1. 代理集合配置
proxy-providers:
  ssrdog:
    url: "你的订阅链接" # 请在此处填入链接
    type: http
    interval: 86400
    health-check: {enable: true, url: "https://www.gstatic.com/generate_204", interval: 300}
    override:
      additional-prefix: "[ssrdog]"
      client-fingerprint: chrome 

proxies: 
  - name: "直连"
    type: direct
    udp: true

mixed-port: 7890
ipv6: true
allow-lan: true
unified-delay: false
tcp-concurrent: true
external-controller: 0.0.0.0:9090
external-ui: ui
external-ui-url: "https://gh-proxy.org/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

geodata-mode: true
geox-url:
  geoip: "https://gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  geosite: "https://gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb"
  asn: "https://gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"

find-process-mode: strict


profile:
  store-selected: true
  store-fake-ip: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"
    - "rule-set:fakeipfilter_domain"

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.market.xiaomi.com"
  default-nameserver:
    - tls://223.5.5.5
    - tls://223.6.6.6
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

proxy-groups:
  - {name: 默认代理, type: select, proxies: [直连, REJECT], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}
  - {name: 国内直连, type: select, proxies: [直连, REJECT], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}
  - {name: 漫画柜, type: select, proxies: [默认代理,直连], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}
  - {name: JavDB, type: select, proxies: [默认代理,直连], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}
  - {name: 禁漫天堂, type: select, proxies: [默认代理,直连], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}
  - {name: DMM, type: select, proxies: [默认代理,直连], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}
  - {name: PickPak, type: select, proxies: [默认代理,直连], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}
  - {name: OpenCode, type: select, proxies: [默认代理,直连], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}
  - {name: YouTube, type: select, proxies: [默认代理,直连], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}
  - {name: Google, type: select, proxies: [默认代理,直连], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}
  - {name: AI, type: select, proxies: [默认代理,直连], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}
  - {name: GitHub, type: select, proxies: [默认代理,直连], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}
  - {name: OneDrive, type: select, proxies: [默认代理,直连], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}
  - {name: Microsoft, type: select, proxies: [默认代理,直连], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}
  - {name: Apple, type: select, proxies: [默认代理,直连], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}
  - {name: TikTok, type: select, proxies: [默认代理,直连], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}
  - {name: Telegram, type: select, proxies: [默认代理,直连], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}
  - {name: NETFLIX, type: select, proxies: [默认代理,直连], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}
  - {name: PayPal, type: select, proxies: [默认代理,直连], include-all: true, filter: "^((?!(GB|Traffic|Expire)).)*$"}

rules:
  - AND,((NETWORK,UDP),(DST-PORT,443)),REJECT
  - GEOSITE,private,国内直连
  - GEOIP,private,国内直连,no-resolve
  - RULE-SET,youtubeapp,YouTube
  - RULE-SET,manhuagui,漫画柜
  - RULE-SET,x18comic,禁漫天堂
  - RULE-SET,dmm,DMM
  - RULE-SET,javdb,JavDB
  - RULE-SET,pikpak,PickPak
  - RULE-SET,opencode,OpenCode
  - RULE-SET,proxylite,默认代理
  - RULE-SET,domestic,国内直连   
  - GEOSITE,category-ai-!cn,AI 
  - GEOSITE,youtube,YouTube
  - GEOSITE,google,Google
  - GEOSITE,github,GitHub
  - GEOSITE,netflix,NETFLIX
  - GEOSITE,telegram,Telegram
  - GEOSITE,tiktok,TikTok
  - GEOSITE,microsoft,Microsoft
  - GEOSITE,apple,Apple
  - GEOSITE,paypal,PayPal         
  - GEOSITE,cn,国内直连                  
  - GEOIP,cn,国内直连,no-resolve         
  - MATCH,默认代理

rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}

rule-providers: 
  proxylite: { <<: *class, url: "https://raw.githubusercontent.com/syaofox/jichang/main/rule-providers/proxy.list"}
  domestic: { <<: *class, url: "https://raw.githubusercontent.com/syaofox/jichang/main/rule-providers/domestic.list"}
  manhuagui: { <<: *class, url: "https://raw.githubusercontent.com/syaofox/jichang/main/rule-providers/manhuagui.list"}
  x18comic: { <<: *class, url: "https://raw.githubusercontent.com/syaofox/jichang/main/rule-providers/18comic.list"}
  dmm: { <<: *class, url: "https://raw.githubusercontent.com/syaofox/jichang/main/rule-providers/dmm.list"}
  javdb: { <<: *class, url: "https://raw.githubusercontent.com/syaofox/jichang/main/rule-providers/javdb.list"}
  pikpak: { <<: *class, url: "https://raw.githubusercontent.com/syaofox/jichang/main/rule-providers/pikpak.list"}
  opencode: { <<: *class, url: "https://raw.githubusercontent.com/syaofox/jichang/main/rule-providers/opencode.list"}
  youtubeapp: { <<: *class, url: "https://raw.githubusercontent.com/syaofox/jichang/main/rule-providers/youtubeapp.list"}
  fakeipfilter_domain: {<<: *domain, url: "https://raw.githubusercontent.com/wwqgtxx/clash-rules/release/fakeip-filter.mrs"}